db_path: "\\databases"
dbnames:
  Kids: "True"
  Philosophy: "True"
  Religion: "True"
  Social Sciences: "True"
  Language: "True"
  Science: "True"
  Technology: "True"
  Arts: "True"
  Literature: "True"
  History, Geography: "True"

